export default {
  nav: [
    { id: 1, text: "Home", href: "/", kind: "page" },
    { id: 2, text: "Content", href: "#", kind: "page" },
    { id: 3, text: "Library", href: "#", kind: "page" },
    { id: 4, text: "Encyclopedia", href: "#", kind: "page" },
    { id: 5, text: "About", href: "#", kind: "page" },
    { id: 6, text: "Donate", href: "#", kind: "page" },
    { id: 7, text: "Contact", href: "#", kind: "page" },
  ],
  tags: [
    { id: 1, slug: "politics", text: "Politics" },
    { id: 2, slug: "environmentalism", text: "Environmentalism" },
    { id: 3, slug: "former-socialism", text: "Former Socialism" },
    { id: 4, slug: "economics", text: "Economics" },
    { id: 5, slug: "advanced-theory", text: "Advanced Theory" },
    { id: 6, slug: "beginner-theory", text: "Beginners Theory" },
    { id: 7, slug: "current-events", text: "Current Events" },
    { id: 8, slug: "society-and-culture", text: "Society & Culture" },
    { id: 9, slug: "philosophy", text: "Philosophy" },
    { id: 10, slug: "history", text: "History" },
  ],
  videos: [
    {
      id: 1,
      slug: "defending-capitalism-is-kinda-pathetic",
      title: "Defending capitalism is kinda pathetic",
      url: "https://youtu.be/F4LOXC9ccNQ",
      description: "Adipisci deserunt cumque sunt ullam magnam provident temporibus animi. Eos eum consequatur perspiciatis inventore praesentiu",
    },
    {
      id: 2,
      slug: "cursed-balkan-history",
      title: "Cursed Balkan history explained",
      url: "https://youtu.be/yLwNIUUmvvs",
      description: "The essence of Balkan history from the Balkan Wars untill today summed up in 1 hour.",
    },
    {
      id: 3,
      slug: "the-balkans-are-disappearing",
      title: "The Balkans are disappearing, quickly",
      url: "https://youtu.be/UeN8NzE5INo",
      description: "Exploring the problem of mass emigration and brain drain from the Balkan penninsula.",
    },
    {
      id: 4,
      slug: "history-of-yugoslavia-through-music",
      title: "History of Yugoslavia through music",
      url: "https://youtu.be/n9TvBAfAYtY",
      description: "Yugoslav history told through popular mass songs which depict this era through melancholy and nostalgia.",
    },
    {
      id: 5,
      slug: "eius-quia-nobis",
      title: "Eius Quia Nobis",
      url: "https://vimeo.com/22960091",
      description: "Debitis adipisci eveniet quae voluptates voluptate nam perferendis nulla. Labore qui id quia tempore vel ",
    },
    {
      id: 6,
      slug: "voluptas-consequatur-in-totam",
      title: "Voluptas Consequatur In Totam",
      url: "https://vimeo.com/68481134",
      description: "Voluptatem qui non quae totam adipisci sit dolor molestias. Voluptatem eligendi praesentium sed alias voluptatem exceptu",
    },
  ],
  creators: [
    {
      name: "Black Power Media",
      slug: "black-power-media",
      avatar: "black-power-media.jpg",
      short_description: "Black Power Media (BPM) is a Black-radical independent media project: We seek to challenge the narrative about Black politics and the Black condition.",
      long_description: "Black Power Media (BPM) is a Black-radical independent media collective: We seek to challenge the narrative about Black politics and the Black condition. Our programming will deliver the news and information our community and others need to break through today's mainstream propaganda machine. BPM calls truth to power and does not hold back on discussing what’s going on at the political, electoral, and grassroots levels of our communities, and provides ideological breakdowns and ways forward for our community.",
      youtube_link: "https://www.youtube.com/@BlackPowerMedia.",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "History", slug: "history", id: 10 },
      ],
      item_id: "648b2ecd4fa82cd3c6ca8b7c",
    },
    {
      name: "Black Red Guard",
      slug: "black-red-guard",
      avatar: "black-red-guard.jpg",
      short_description: "Ruminations, rants, game shit, lectures and screeds from a Communist in the Midwest.",
      long_description: "",
      youtube_link: "https://www.youtube.com/@betterredthandead9105",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "648b2e0f087edb9b8f00a87c",
    },
    {
      name: "Leslie Fluette",
      slug: "leslie-fluette",
      avatar: "leslie-fluette.jpg",
      short_description: "I'm Leslie and on this channel I discuss all kinds of issues from a leftist perspective.",
      long_description: "",
      youtube_link: "https://www.youtube.com/@lesliefluette1784",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Philosophy", slug: "philosophy", id: 9 },
      ],
      item_id: "648b2a245c45fe2ade4687cb",
    },
    {
      name: "Black Bolshevik",
      slug: "black-bolshevik",
      avatar: "black-bolshevik.jpg",
      short_description: "On this channel various subjects such as art, literature, pop culture, geopolitics, media and economics is covered using a Marxian/Third Worldist/Post-Colonialist/Pan-Africanist comprehension.",
      long_description: "On this channel various subjects such as art, literature, pop culture, geopolitics, media and economics is covered using a Marxian/Third Worldist/Post-Colonialist/Pan-Africanist comprehension. In this analysis, I also attempt to provide solutions to these issues to the best of my knowledge and according to my research. However, my analysis may not always be viable or feasible, thus I suggest using my videos as merely a form of thought-provoking framework in which you can apply your own analysis based on what best suits your material conditions.",
      youtube_link: "https://www.youtube.com/@theblackbolshevik/",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Africa",
      tags: [
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "History", slug: "history", id: 10 },
      ],
      item_id: "648a12c96386e84471ea0d47",
    },
    {
      name: "Prolekult",
      slug: "prolekult",
      avatar: "prolekult.jpg",
      short_description: "The purpose of the project is to provide high-quality film content looking at world politics, culture and economics from a Marxist perspective.",
      long_description: "",
      youtube_link: "https://www.youtube.com/@Prolekult",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "6489b927f00c2c97f6956da7",
    },
    {
      name: "Fellow Traveler",
      slug: "fellow-traveler",
      avatar: "fellow-traveler.jpg",
      short_description: "Welcome to my channel! This is a place where we talk about politics, economics, history, and philosophy from a communist perspective.",
      long_description: "This is a place where we talk about politics, economics, history, and philosophy from a real communist perspective. Here we debunk liberal and fascist distortions and falsehoods about socialism, expose opportunists and phony leftists, educate people about the truth of communism as well as marxist theory, comment on current events, radicalize working people, produce leftist propaganda and miniature documentaries, and have fun along the way.",
      youtube_link: "https://www.youtube.com/@fellowtraveler2251",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "6489b432d6cee7fa0fa0df37",
    },
    {
      name: "Tom Nicholas",
      slug: "tom-nicholas",
      avatar: "tom-nicholas.jpg",
      short_description: "I make videos which explore the intersection between politics and culture. Expect videos which, usually, foster fascinating conversations in the comments.",
      long_description: "I make videos which explore the intersection between politics and culture.\n\nCurrently, my work can be divided into two main categories: my What the Theory? series, in which I aim to provide engaging introductions to key theories and concepts in cultural studies and the wider humanities, and my Video Essays, in which I more broadly prod and poke at the world we live in today.\n\nExpect videos which foster fascinating conversations in the comments.",
      youtube_link: "https://www.youtube.com/@Tom_Nicholas",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "6489b354076bf13f2e4c231f",
    },
    {
      name: "FDSignifier",
      slug: "fdsignifier",
      avatar: "fdsignifier.jpg",
      short_description: "A channel that focuses on black history, activism",
      long_description: "",
      youtube_link: "",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Select an option...",
      tags: [],
      item_id: "6489b23f6fca68223ae66f45",
    },
    {
      name: "On the Shoulders of Giants",
      slug: "on-the-shoulders-of-giants",
      avatar: "on-the-shoulders-of-giants.jpg",
      short_description: "On the Shoulders of Giants uploads videos teaching you about the lives of sung and unsung heroes of the African diaspora, heroes we normally wouldn’t learn about.",
      long_description: "On the Shoulders of Giants uploads videos teaching you about the lives of sung and unsung heroes of the African diaspora, heroes we normally wouldn’t learn about. We read books weekly, by African scholars who have provided us with valuable information we can use to improve our communities. We also break down clips of lectures, interviews, and conversations of black scholars, leaders, historians, etc.\n\nOn the Shoulders of Giants understands that it is important to recognize and be aware of the contributions of those before us, especially those of African or Indigenous descent.We not only provide you with information about our heroes and the philosophies of our heroes, but we also break the information down in an entertaining fashion, so we can understand and use the information to better our lives.",
      youtube_link: "",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Africa",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "6485e91ae76a651c49086106",
    },
    {
      name: "Halim Alrah",
      slug: "halim-alrah",
      avatar: "halim-alrah.jpg",
      short_description: "High-production value videos from an afro-asian socialist about marxist theory, the nature of news media, and the current state of capitalism.",
      long_description: "",
      youtube_link: "https://www.youtube.com/@halimalrah2105/featured",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Economics", slug: "economics", id: 4 },
      ],
      item_id: "6485e4c1c9a80f3e6cf66ef9",
    },
    {
      name: "Sam Sinha",
      slug: "sam-sinha",
      avatar: "sam-sinha.jpg",
      short_description: "Semi-documentaries from a materialist perspective, featuring videos on marxism, electoralism, history, consumerism, and more. ",
      long_description: "",
      youtube_link: "https://www.youtube.com/@SamSinha",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Economics", slug: "economics", id: 4 },
      ],
      item_id: "6485dfbadad1e51711b0e66e",
    },
    {
      name: "NonCompete",
      slug: "noncompete",
      avatar: "noncompete.jpg",
      short_description: "Non-Compete is a channel and collective creating educational and entertainment contact from a radical left-wing perspective.",
      long_description: "Non-Compete is a channel creating educational and entertainment contact from a radical left-wing perspective, delivering video essays, interviews and documentaries, and other material which explores anarchist and communist philosophy, theory, and praxis and highlights the work of comrades around the world in the battle against oppression of all forms.\n\nOur channels include:\n\nNon-Compete\n\nBreadville\n\nNon-Compete Live\n\nLuna OiLuna Live\n\nSlopstache",
      youtube_link: "https://www.youtube.com/@NonCompete/featured",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "North America",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "6485dd55ffbff1d8131119e8",
    },
    {
      name: "Historical Sense",
      slug: "historical-sense",
      avatar: "historical-sense.jpg",
      short_description: "This channel features videos that instill viewers with a historical sense of the misconceptions and myths about the past that inform present concerns, issues, and debates",
      long_description: "History is everywhere. It inspires political projects such as the Green New Deal, echoes in slogans such as “Make America Great Again,” and provokes conflicts over public monuments, race, foreign policy, labor, regulation, the environment, and inequality. This channel features videos that instill viewers with a historical sense of the misconceptions and myths about the past that inform present concerns, issues, and debates.",
      youtube_link: "",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "North America",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "6485daea21f08a124eb9df38",
    },
    {
      name: "Democracy At Work",
      slug: "democracy-at-work",
      avatar: "democracy-at-work.jpg",
      short_description: "Democracy at Work is a non-profit 501(c)3 that produces media and live events. Their work analyzes capitalism critically as a systemic problem and advocates for democratizing workplaces as part of a systemic solution.",
      long_description: "Democracy at Work is a non-profit 501(c)3 that produces anti-capitalist, progressive media. Our work analyzes our capitalist economy critically as a systemic problem and advocates for democratizing workplaces as part of a systemic solution. We seek a stronger, fuller democracy – in our politics, culture and workplaces - based on equal collaboration and shared leadership by workers inside enterprises and throughout society.",
      youtube_link: "https://www.youtube.com/@democracyatwrk/featured",
      instagram_link: "https://www.instagram.com/democracyatwrk/",
      twitter_link: "https://twitter.com/democracyatwrk",
      patreon_link: "https://www.patreon.com/democracyatwork",
      geofocus: "Global",
      tags: [],
      item_id: "6484b25404a49cc6fcaa0dee",
    },
    {
      name: "The Gravel Institute",
      slug: "the-gravel-institute",
      avatar: "the-gravel-institute.jpg",
      short_description: "With concise 5-minute videos from authoritative presenters (from Bernie Sanders to Chelsea Manning), we're pushing nontraditional audiences to the left.",
      long_description: "We're building the infrastructure to beat right-wing propaganda outlets like PragerU on their own turf. With concise 5-minute videos from authoritative presenters (from Bernie Sanders to Chelsea Manning), we're pushing nontraditional audiences to the left. And to fight a behemoth like Prager—with huge ad budgets and millions of subscribers—we need you on board. Join us.",
      youtube_link: "https://www.youtube.com/@TheGravelInstitute",
      instagram_link: "https://www.instagram.com/gravelinstitute/",
      twitter_link: "https://twitter.com/GravelInstitute",
      patreon_link: "https://www.patreon.com/gravelinstitute",
      geofocus: "North America",
      tags: [],
      item_id: "6484b1cca71d38fbbe274d5c",
    },
    {
      name: "Lady Izdihar",
      slug: "lady-izdihar",
      avatar: "lady-izdihar.jpg",
      short_description: "Lady Izdihar is a historian, youtuber and tiktoker who looks at life in Soviet Russia. She likes to share the fashion and lifestyles of common people within Soviet Russia, often through a Muslim perspective.",
      long_description: "Asalam alaikum comrades! I'm a historian on Russian history but mostly focus on the first 30-40 years and the cultural and ethnographic makeup of what the USSR was.\n\nI'm all about humanization and covering the positive aspects of Soviet & Russian history as that's what's missing in the English language, the lesser known, misunderstood and misrepresented.",
      youtube_link: "https://www.youtube.com/@LadyIzdihar/videos",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "Eastern Europe",
      tags: [],
      item_id: "6484b1753ed63cf35416a5df",
    },
    {
      name: "Real Progressives",
      slug: "real-progressives",
      avatar: "real-progressives.jpg",
      short_description: "Real Progressives strives to be a primary source of reliable, credible, progressive news and information in order to mobilize positive change in the world.",
      long_description: "Real Progressives strives to be a primary source of reliable, credible, progressive news and information in order to mobilize positive change in the world.\n\nWe provide multiple platforms for dissemination of progressive policy and Modern Monetary Theory (MMT) and concepts to a wide public audience providing clarity and understanding like no other media organization. Our global audience of progressives span the political spectrum and are comprised of diverse educational and occupational  backgrounds.\n\nWe seek to unify peoples within a framework of accurate and credible reporting, insightful commentary and consulting expertise that provides monetary policy education vital to the development of effective, moral policy and an educated public.",
      youtube_link: "https://www.youtube.com/@RealProgressives/videos",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "",
      geofocus: "North America",
      tags: [],
      item_id: "6484b0f14619a4f77cf9b1ef",
    },
    {
      name: "Sublation Media",
      slug: "sublation-media",
      avatar: "sublation-media.jpg",
      short_description: "Sublation Media includes book publishing, a magazine, youtube videos that introduce and explore ideas from critical theory, and podcasts.",
      long_description: "Why Are We called Sublation? As per Google: \"In sublation, a term or concept is both preserved and changed through its dialectical interplay with another term or concept. Sublation is the motor by which the dialectic functions. Sublation can be seen at work at the most basic level of Hegel's system of logic.\"This new company aims at making left and socialist theory more accessible than its name and at avoiding the worst aspects of leftist culture.\n\nWe intend to attempt to sublate the contradictions we find both in our own ranks and in the larger world.Sublation Media includes book publishing,  a magazine, youtube videos that introduce and explore ideas from critical theory, and podcasts where we will try to enjoy each other's company even as we interrogate each other and argue.",
      youtube_link: "https://www.youtube.com/@sublationmedia",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "https://patreon.com/dietsoap",
      geofocus: "Global",
      tags: [],
      item_id: "6484b02ca7baf73f86cb6ef6",
    },
    {
      name: "Chill Goblin",
      slug: "chill-goblin",
      avatar: "chill-goblin.jpg",
      short_description: "I'm Chill Goblin. I'm doing my best to make well-researched & thought-provoking leftist videos, but to be honest I'm probably funnier than I am smart.",
      long_description: "I’m Chill Goblin. I started my YouTube channel when the pandemic hit and I couldn’t do standup comedy anymore. My videos are like if Prager U dropped acid and got better politics. I'm doing my best to make well-researched & thought-provoking leftist videos often through the lens of critical theory, but to be honest I'm probably funnier than I am smart. Hopefully you can at least get some entertainment out of them.",
      youtube_link: "https://www.youtube.com/@ChillGoblin",
      instagram_link: "",
      twitter_link: "https://twitter.com/Chill_Goblin",
      patreon_link: "https://www.patreon.com/ChillGoblin",
      geofocus: "Global",
      tags: ["Philosophy", "Beginners theory", "Environmentalism"],
      item_id: "6484aefabcaaa4bf82e44698",
    },
    {
      name: "Epoch Philosophy",
      slug: "epoch-philosophy",
      avatar: "epoch-philosophy.jpg",
      short_description: "Analyses of film, video games, pop culture and more through the lens of critical theory.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@epochphilosophy",
      instagram_link: "https://www.instagram.com/epochphilosophy/",
      twitter_link: "https://twitter.com/EpochPhilosophy",
      patreon_link: "",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
      ],
      item_id: "64516e8eb35ca57bda5823bc",
    },
    {
      name: "Plastic Pills",
      slug: "plastic-pills",
      avatar: "plastic-pills.jpg",
      short_description: "PlasticPills is a channel featuring critical theory and philosophical analyses of culture.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@PlasticPills",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/plasticpills",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
      ],
      item_id: "64516e09082667ab3536303e",
    },
    {
      name: "Luna oi!",
      slug: "luna-oi",
      avatar: "luna-oi.jpg",
      short_description: "Luna Oi is a Marxist-Leninist from Vietnam. Her content focuses on life in socialist Vietnam as well as Vietnam's history.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@Lunaoi/featured",
      instagram_link: "",
      twitter_link: "https://twitter.com/lunaoi_vn/",
      patreon_link: "https://www.patreon.com/lunaoi",
      geofocus: "East Asia",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "64516d5a93e7c88cab21afa4",
    },
    {
      name: "Thought Slime",
      slug: "thought-slime",
      avatar: "thought-slime.jpg",
      short_description: "Youtube channel with a focus on current events, and personal stories relating to life under capitalism.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@ThoughtSlime",
      instagram_link: "",
      twitter_link: "https://twitter.com/thoughtslime",
      patreon_link: "https://www.patreon.com/thoughtslime",
      geofocus: "Global",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
      ],
      item_id: "64516cdad731c8111842a326",
    },
    {
      name: "Boy Boy",
      slug: "boy-boy",
      avatar: "boy-boy.jpg",
      short_description: "Two Australians that like to uncover the darker sides of Austrailian politics, as well as politics around the globe.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@Boy_Boy/featured",
      instagram_link: "",
      twitter_link: "https://twitter.com/BoyBoy_Official",
      patreon_link: "https://www.patreon.com/Boy_Boy",
      geofocus: "Global",
      tags: [
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
      ],
      item_id: "64516c69e6046881047e5708",
    },
    {
      name: "Jonas Ceika - CCK Philosophy",
      slug: "jonas-ceika-cck-philosophy",
      avatar: "jonas-ceika-cck-philosophy.jpg",
      short_description: "A youtuber that makes videos on philosophy, politics, history and cultural theory.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@jonasceikaCCK/featured",
      instagram_link: "",
      twitter_link: "https://twitter.com/PhilosophyCuck",
      patreon_link: "https://www.patreon.com/cuck",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Advanced Theory", slug: "advanced-theory", id: 5 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "History", slug: "history", id: 10 },
      ],
      item_id: "64516ba062e55d5a70148912",
    },
    {
      name: "Think That Through",
      slug: "think-that-through",
      avatar: "think-that-through.jpg",
      short_description: "Channel with a heavy focus on topics relating to ecology: specifically topics like climate change, degrowth and solar punk.",
      long_description: "The climate is changing – and the way we think needs to keep up.Postmodernism? Bah, that's so 20th century! Our main goal is to make the modern climate philosophy as accessible as possible, with topics like Anthropocene, Capitalocene, Chtulucene, Degrowth, hyperobjects or new materialism, or solarpunk.\n\nUnfortunately, some of these writers tend to be very opaque or academic – which makes sense if we consider that they're struggling with finding completely new ways of thinking. And this is where we come in: we read them, so you don't have to! Offering approachable and easily digestible videos on difficult topics.",
      youtube_link: "https://www.youtube.com/@t3essays/featured",
      instagram_link: "",
      twitter_link: "https://twitter.com/t3essays",
      patreon_link: "https://www.patreon.com/join/ThinkThatThrough",
      geofocus: "Global",
      tags: [
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "64516b202e93b20ecbb7283a",
    },
    {
      name: "Mexie",
      slug: "mexie",
      avatar: "mexie.jpg",
      short_description: "Mexie focuses on topics such as disability, chronic illness, sex, ecology, and life under capitalism. She also runs a second channel called 'Positive Leftist News'.",
      long_description: "I'm a post-doc, lecturer and gardener in Toronto with chronic illness and too many jobs. My PhD is in human geography / political ecology, focusing on the intersections between political economy and global environmental governance. This sobering experience has led me to be the staunch anti-capitalist, total liberation activist you see today!\nI make educational videos about political economy/capitalism, environmental issues, human and animal liberation, decolonization, and issues relating to social/economic justice. I felt like talking to academics about subjects we tended to agree upon wasn't having as much impact as possible. Why not use my research to educate, agitate & organize?!I also host a podcast, Total Liberation, with my friend and comrade Marine: www.totalliberationpodcast.comI've also started a new channel for Positive Leftist News: https://www.youtube.com/c/PLN_mex",
      youtube_link: "https://www.youtube.com/@Mexie/featured",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/mexie",
      geofocus: "Global",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "645169fe0826676b5335e27f",
    },
    {
      name: "azureScapegoat",
      slug: "azurescapegoat",
      avatar: "azurescapegoat.jpg",
      short_description: "AzureScapeGoat make educational videos about politics from a Marxist perspective.",
      long_description: "I'm the creator of Socialism101.com and the azureScapegoat YouTube channel. I also stream on Twitch.tv/azureScapegoat.",
      youtube_link: "https://www.youtube.com/@azureScapegoat",
      instagram_link: "",
      twitter_link: "https://twitter.com/azurescapegoat",
      patreon_link: "https://www.patreon.com/azurescapegoat",
      geofocus: "Global",
      tags: [
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
      ],
      item_id: "64516948700faf7e5f965483",
    },
    {
      name: "Our Changing Climate",
      slug: "our-changing-climate",
      avatar: "our-changing-climate.jpg",
      short_description: "Our Changing Climate is a video essay series dedicated to examining our relationship to the natural world from a socialist perspective.",
      long_description: "Our Changing Climate is a video essay series dedicated to examining our relationship to the natural world.\n\nOur Changing Climate (OCC) seeks to fill a void I have noticed recently in the media: a lack of coverage of all things environmental. I started Our Changing Climate to not only analyze the various ways in which the natural world affects our lives, but also to spark much-needed discussion on environmental topics.",
      youtube_link: "https://www.youtube.com/@OurChangingClimate",
      instagram_link: "https://www.instagram.com/occ.climate/",
      twitter_link: "https://twitter.com/OurClimateNow",
      patreon_link: "https://www.patreon.com/OurChangingClimate",
      geofocus: "Global",
      tags: [
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "6451683828ef970c836d4999",
    },
    {
      name: "Andrewism",
      slug: "andrewism",
      avatar: "andrewism.png",
      short_description: "I run a Youtube channel called Andrewism, where I share what I've been learning and thinking about politics, art, history, anarchy, and whatever else really.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@Andrewism/",
      instagram_link: "",
      twitter_link: "https://twitter.com/_saintdrew",
      patreon_link: "https://www.patreon.com/saintdrew",
      geofocus: "Global",
      tags: [
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
      ],
      item_id: "644cecd5bc0ae1190309ea3c",
    },
    {
      name: "Marxism Today",
      slug: "marxism-today",
      avatar: "marxism-today.jpg",
      short_description: "Left-wing political educational content, video essays, history, cultural analysis and more from a modern Irish socialist republican, Marxist perspective.",
      long_description: "Marxism Today is an independent Irish socialist republican media outlet which creates and releases YouTube videos as part of the larger socialist project of Agitating, Educating and Organising.",
      youtube_link: "https://www.youtube.com/@Marxism_Today/",
      instagram_link: "",
      twitter_link: "https://twitter.com/MarxistPaul",
      patreon_link: "https://www.patreon.com/MarxistPaul",
      geofocus: "Global",
      tags: [
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "History", slug: "history", id: 10 },
        { name: "Current events", slug: "current-events", id: 7 },
      ],
      item_id: "644bd3dc1e4fee1f38d3b7da",
    },
    {
      name: "BadEmpanada",
      slug: "badempanada",
      avatar: "badempanada.jpg",
      short_description: "Videos on history, politics, society & culture, covering a broad array of topics in depth, especially relating to South America.",
      long_description: "Hello everyone! I make videos on my YouTube channel. They cover politics, history, society, etc, with an emphasis on covering things outside of the normal focus on the US/Europe. I also have a Twitch stream where I cover these same topics, and a second channel where I upload more off-the-cuff videos.I studied History and Politics, and considered pursuing an academic career.\n\nHowever, the main audience of academic research is other academics, and while I think they do very valuable work, its inaccessibility conflicts with my personal ethics. The content of these paywalled journals and prohibitively expensive books are out of reach of most people, but I believe they are so important that they should be accessible to everyone. That's why I decided to make a YouTube channel instead: to make videos that anyone can watch, with the freedom to cover a much broader range of topics.",
      youtube_link: "",
      instagram_link: "https://www.instagram.com/BadEmpanada/",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/BadEmpanada",
      geofocus: "Latin America",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "644bd2c357085827d4d92e2c",
    },
    {
      name: "HasanAbi",
      slug: "hasanabi",
      avatar: "hasanabi.jpg",
      short_description: "Twitch streamer and online influencer that covers current events and news from a left-wing, humorous perspective.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@HasanAbi",
      instagram_link: "",
      twitter_link: "https://twitter.com/hasanthehun",
      patreon_link: "",
      geofocus: "North America",
      tags: [
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "644bd1a3cbad957e90c8f32b",
    },
    {
      name: "Bes D Marx",
      slug: "bes-d-marx",
      avatar: "bes-d-marx.jpg",
      short_description: "Bes D Marx is an Albanian youtuber who does deep dives into the history of socialist movements, particularly in Europe.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@BesDMarx/",
      instagram_link: "",
      twitter_link: "https://twitter.com/BesDMarx",
      patreon_link: "",
      geofocus: "Europe",
      tags: [
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
      ],
      item_id: "644bcec1be660b547e58fb17",
    },
    {
      name: "1Dime",
      slug: "1dime",
      avatar: "1dime.jpg",
      short_description: "1Dime is an educational channel dedicated to countering one dimensional thought by exploring world issues and social-political topics through many lens.",
      long_description: "1Dime is an educational channel dedicated to countering one dimensional thought by exploring world issues and social-political topics through the lens of history, geopolitics, political theory, philosophy, economics, and pop culture. Each new video is a unique artistic experiment with extensive effort put into the production value. We make learning stuff fun by dissolving the distinction between art, education, and entertainment.",
      youtube_link: "https://www.youtube.com/@1Dimee",
      instagram_link: "",
      twitter_link: "https://twitter.com/1DimeOfficial",
      patreon_link: "https://www.patreon.com/OneDime",
      geofocus: "Global",
      tags: [
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "History", slug: "history", id: 10 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
      ],
      item_id: "644bce635c010616f3ba0263",
    },
    {
      name: "The Marxist Project",
      slug: "the-marxist-project",
      avatar: "the-marxist-project.jpg",
      short_description: "The Marxist Project is primarily an educational YouTube channel whose main goal is to present and discuss various concepts in Marxist theory.",
      long_description: "The Marxist Project is primarily an educational YouTube channel whose main goal is to present and discuss various concepts in Marxist theory. The channel focuses on the fundamentals, as well as the application of Marxist theory to modern day issues. The research, scripting, art, audio recording, and editing is all mostly done by one person. Because this is (usually) a one-man-act, and because resources are very limited, video production is slow.",
      youtube_link: "",
      instagram_link: "",
      twitter_link: "https://twitter.com/MarxistProject",
      patreon_link: "https://www.patreon.com/themarxistproject",
      geofocus: "Global",
      tags: [
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Advanced Theory", slug: "advanced-theory", id: 5 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Economics", slug: "economics", id: 4 },
      ],
      item_id: "644bb54ab44a8c6d72fd5d7f",
    },
    {
      name: "ChemicalMind",
      slug: "chemicalmind",
      avatar: "chemicalmind.jpg",
      short_description: "Youtuber focusing on current events, former and current socialist states, deep ecology, cultural analysis, and various other historical topics.",
      long_description: "Hi there, I'm Chem. I'm a writer, educator, and budding video essayist. I regularly create heavily researched videos about whatever my special interest is at the moment covering a wide-range of topics--and always with a Marxist, anti-imperialist angle of analysis.",
      youtube_link: "https://www.youtube.com/@chemreac1",
      instagram_link: "",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/ChemicalReaction",
      geofocus: "Global",
      tags: [
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "History", slug: "history", id: 10 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Environmentalism", slug: "environmentalism", id: 2 },
      ],
      item_id: "644bb4a9fac08dca9a0f505c",
    },
    {
      name: "Yugopnik",
      slug: "yugopnik",
      avatar: "yugopnik.jpg",
      short_description: "Yugopnik is a Balkan creator whose videos focus on topics like analyzing Nazism, Yugoslavic history, and consumerism.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@YUGOPNIK/",
      instagram_link: "",
      twitter_link: "https://twitter.com/yugopnik",
      patreon_link: "https://www.patreon.com/yugopnik",
      geofocus: "Global",
      tags: [
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Philosophy", slug: "philosophy", id: 9 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
      ],
      item_id: "644bb410fac08d92a60f3e03",
    },
    {
      name: "Hakim",
      slug: "hakim",
      avatar: "hakim.png",
      short_description: "Hakim is an Iraqi youtuber with a special interest in the history of the USSR as well as in economics.",
      long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum. Integer blandit tincidunt ex, id molestie leo ornare a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar felis a neque mattis bibendum.",
      youtube_link: "https://www.youtube.com/@YaBoiHakim",
      instagram_link: "",
      twitter_link: "https://twitter.com/YaBoiHakim",
      patreon_link: "https://www.patreon.com/ComradeHakim",
      geofocus: "Global",
      tags: [
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "History", slug: "history", id: 10 },
      ],
      item_id: "644bb33c484985535a956765",
    },
    {
      name: "Second Thought",
      slug: "second-thought",
      avatar: "second-thought.jpg",
      short_description: "Second Thought was originally a general interest pop-science channel before transitioning towards a focus on general interest anti-capitalist content instead.",
      long_description: 'The goal of my channel is to help people over that initial hurdle of "socialism bad." We\'ve all heard that line for years. It was drilled into us at school, our parents still repeat Red Scare propaganda, and much of the world has completely given up on the belief that a better world is possible. But not us. We know that by working together to fight back against the inhuman greed of capitalism, we can change the world. We can move beyond the system that puts profits over human flourishing. We can make life worth living.',
      youtube_link: "https://www.youtube.com/@SecondThought/",
      instagram_link: "",
      twitter_link: "https://twitter.com/_SecondThought",
      patreon_link: "https://www.patreon.com/secondthought",
      geofocus: "North America",
      tags: [
        { name: "Current events", slug: "current-events", id: 7 },
        { name: "Beginners theory", slug: "beginner-theory", id: 6 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
        { name: "Politics", slug: "politics", id: 1 },
        { name: "Economics", slug: "economics", id: 4 },
      ],
      item_id: "644bb2abb44a8c7041fd3780",
    },
    {
      name: "Balkan Odyssey",
      slug: "balkan-odyssey",
      avatar: "balkan-odyssey.jpg",
      short_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism.",
      long_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism. Merely understanding the status quo isn't enough if we don't take action to change it.\n\nThat's where the conclusions of this dialectical analysis provide us with answers of what is to be done, concretely. Become a part of a new generation of people who reject national-chauvinism, ethnonationalism, tribalism, the oppresion of women, minorities, gay and trans people - while advocating for a more progressive society and the building of socialism in our lifetime.",
      youtube_link: "https://www.youtube.com/@BalkanOdyssey_",
      instagram_link: "https://www.instagram.com/balkan.odyssey/",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/BalkanOdyssey",
      geofocus: "Balkans",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "644bb0e3be660bcb4557058d",
    },
    {
      name: "Balkan Odyssey",
      slug: "balkan-odyssey",
      avatar: "balkan-odyssey.jpg",
      short_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism.",
      long_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism. Merely understanding the status quo isn't enough if we don't take action to change it.\n\nThat's where the conclusions of this dialectical analysis provide us with answers of what is to be done, concretely. Become a part of a new generation of people who reject national-chauvinism, ethnonationalism, tribalism, the oppresion of women, minorities, gay and trans people - while advocating for a more progressive society and the building of socialism in our lifetime.",
      youtube_link: "https://www.youtube.com/@BalkanOdyssey_",
      instagram_link: "https://www.instagram.com/balkan.odyssey/",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/BalkanOdyssey",
      geofocus: "Balkans",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "644bb0e3be660bcb4557058d",
    },
    {
      name: "Balkan Odyssey",
      slug: "balkan-odyssey",
      avatar: "balkan-odyssey.jpg",
      short_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism.",
      long_description: "Exploring the realms of the past - conjuring a path for the future. This line probably best explains the nature and virtue of my content, as I attempt to make sense of the shitshow known as Balkan politics and history through the lens of Marxism. Merely understanding the status quo isn't enough if we don't take action to change it.\n\nThat's where the conclusions of this dialectical analysis provide us with answers of what is to be done, concretely. Become a part of a new generation of people who reject national-chauvinism, ethnonationalism, tribalism, the oppresion of women, minorities, gay and trans people - while advocating for a more progressive society and the building of socialism in our lifetime.",
      youtube_link: "https://www.youtube.com/@BalkanOdyssey_",
      instagram_link: "https://www.instagram.com/balkan.odyssey/",
      twitter_link: "",
      patreon_link: "https://www.patreon.com/BalkanOdyssey",
      geofocus: "Balkans",
      tags: [
        { name: "History", slug: "history", id: 10 },
        { name: "Former socialism", slug: "former-socialism", id: 3 },
        { name: "Economics", slug: "economics", id: 4 },
        { name: "Society & culture", slug: "society-and-culture", id: 8 },
      ],
      item_id: "644bb0e3be660bcb4557058d",
    },
  ],
};
